Metrics/LineLength:
  Max: 130

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/carthage-play'
    - 'bin/playground'
    - 'lib/cocoapods-playgrounds/generate.rb'
    - 'lib/cocoapods-playgrounds/workspace.rb'
    - 'lib/cocoapods-playgrounds/command/playgrounds.rb'

Style/FileName:
  Exclude:
    - 'lib/cocoapods-playgrounds.rb'

Lint/Void:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150
